"use client";
import {useMemo,useRef,useState} from "react";
import {Camera,CheckCircle2,FilePlus2,Loader2,Send,Trash2,UploadCloud} from "lucide-react";
import {enhance,fileToImage,imageToCanvas} from "@/lib/scanner";
type Attachment={id:string;file:File;preview:string};type Result={ok?:boolean;error?:string;folderId?:string;sessionKey?:string};type Part={blob:Blob;name:string;page:number};
const MAX_FILES=5,MAX_BYTES=10*1024*1024,MAX_AI_PAGES=20;
const RECEIVER_URL="https://script.google.com/macros/s/AKfycbyYPWMNlTcbdwrt4F5j5HmG16Ayc322UK6UhOCv74Vuqs7c2QkY-66kBnGEmi1F4KObTg/exec";
const uid=()=>crypto.randomUUID();
function reference(){const d=new Date(),p=(n:number)=>String(n).padStart(2,"0");return `AKB${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${uid().slice(0,6).toUpperCase()}`}
async function b64(blob:Blob){const bytes=new Uint8Array(await blob.arrayBuffer());let value="";for(let i=0;i<bytes.length;i+=32768)value+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(value)}
async function post(body:Record<string,unknown>):Promise<Result>{const r=await fetch(RECEIVER_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)}),text=await r.text();let data:Result={};try{data=JSON.parse(text) as Result}catch{}if(!r.ok||!data.ok)throw new Error(data.error||text||`HTTP ${r.status}`);return data}
async function cleanImage(file:File){const img=await fileToImage(file),s=Math.min(1,2200/Math.max(img.naturalWidth,img.naturalHeight)),canvas=imageToCanvas(img,Math.round(img.naturalWidth*s),Math.round(img.naturalHeight*s)),cleaned=enhance(canvas,"auto",65);return new Promise<Blob>((yes,no)=>cleaned.toBlob(x=>x?yes(x):no(new Error("ছবি পরিষ্কার করা যায়নি।")),"image/jpeg",.9))}
function parsePages(value:string,total:number){if(!value.trim())return Array.from({length:total},(_,i)=>i+1);if(!/^\d+(?:-\d+)?(?:\s*,\s*\d+(?:-\d+)?)*$/.test(value.trim()))throw new Error("পৃষ্ঠা লিখুন 1, 1-3 অথবা 1-3,5 এইভাবে।");const result=new Set<number>();for(const token of value.split(",")){const [a,b]=token.trim().split("-").map(Number),end=b??a;if(a<1||end<a)throw new Error(`পৃষ্ঠা নির্বাচন সঠিক নয়: ${token}`);for(let n=a;n<=end;n++){if(n>total)throw new Error(`পৃষ্ঠা ${n} নেই। মোট ${total} পৃষ্ঠা আছে।`);result.add(n)}}if(result.size>MAX_AI_PAGES)throw new Error(`AI/OCR-এর জন্য সর্বোচ্চ ${MAX_AI_PAGES}টি পৃষ্ঠা নির্বাচন করুন।`);return [...result].sort((a,b)=>a-b)}
async function analysisParts(files:Attachment[],expression:string):Promise<Part[]>{
 if(!expression.trim())return [];
 const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="/pdf.worker.min.mjs";
 type Pdf=Awaited<ReturnType<typeof pdfjs.getDocument>["promise"]>;const entries:Array<{item:Attachment;start:number;count:number;pdf?:Pdf}>=[];let total=0;
 for(const item of files){if(item.file.type==="application/pdf"){const pdf=await pdfjs.getDocument({data:await item.file.arrayBuffer()}).promise;entries.push({item,start:total+1,count:pdf.numPages,pdf});total+=pdf.numPages}else{entries.push({item,start:++total,count:1})}}
 const out:Part[]=[];for(const n of parsePages(expression,total)){const e=entries.find(x=>n>=x.start&&n<x.start+x.count);if(!e)continue;if(!e.pdf){out.push({blob:e.item.file,name:`page-${n}-${e.item.file.name}`,page:n});continue}const page=await e.pdf.getPage(n-e.start+1),base=page.getViewport({scale:1}),vp=page.getViewport({scale:Math.min(2.5,1800/Math.max(base.width,base.height))}),canvas=document.createElement("canvas");canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);await page.render({canvas,canvasContext:canvas.getContext("2d")!,viewport:vp}).promise;const blob=await new Promise<Blob>((yes,no)=>canvas.toBlob(x=>x?yes(x):no(new Error("PDF পৃষ্ঠা প্রস্তুত করা যায়নি।")),"image/jpeg",.88));out.push({blob,name:`page-${n}.jpg`,page:n})}return out;
}
export default function SubmitPage(){
 const camera=useRef<HTMLInputElement>(null),picker=useRef<HTMLInputElement>(null);const [name,setName]=useState(""),[mobile,setMobile]=useState(""),[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[selection,setSelection]=useState("");const [clean,setClean]=useState(false),[ocr,setOcr]=useState(true),[autoSubject,setAutoSubject]=useState(true),[files,setFiles]=useState<Attachment[]>([]),[busy,setBusy]=useState(false),[state,setState]=useState<"idle"|"ok"|"error">("idle"),[notice,setNotice]=useState("");const total=useMemo(()=>files.reduce((n,x)=>n+x.file.size,0),[files]);
 function add(list:FileList|null){if(!list?.length)return;const accepted=Array.from(list).filter(f=>["image/jpeg","image/png","image/webp","application/pdf"].includes(f.type)),room=MAX_FILES-files.length,next=[...files,...accepted.slice(0,room).map(file=>({id:uid(),file,preview:file.type.startsWith("image/")?URL.createObjectURL(file):""}))];if(next.reduce((n,x)=>n+x.file.size,0)>MAX_BYTES){setState("error");setNotice("সব সংযুক্তি মিলিয়ে সর্বোচ্চ 10 MB রাখা যাবে।");return}setFiles(next);if(accepted.length>room){setState("error");setNotice("সর্বোচ্চ 5টি ফাইল সংযুক্ত করা যাবে।")}}
 function remove(id:string){setFiles(v=>{const x=v.find(y=>y.id===id);if(x?.preview)URL.revokeObjectURL(x.preview);return v.filter(y=>y.id!==id)})}
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim()||!mobile.trim()||!message.trim()){setState("error");setNotice("নাম, মোবাইল নম্বর এবং বক্তব্য পূরণ করুন।");return}if(!files.length){setState("error");setNotice("কমপক্ষে একটি ছবি বা PDF সংযুক্ত করুন।");return}setBusy(true);setState("idle");try{setNotice("পৃষ্ঠা যাচাই করা হচ্ছে...");const parts=(ocr||autoSubject)?await analysisParts(files,selection):[],ref=reference(),note=[`মোবাইল: ${mobile.trim()}`,subject.trim()?`বিষয়: ${subject.trim()}`:"",`বক্তব্য: ${message.trim()}`].filter(Boolean).join("\n"),options={enhance:clean,extractText:ocr,autoSubject,pageSelection:selection.trim()},started=await post({action:"start",reference:ref,name:name.trim(),note,options}),folderId=String(started.folderId||""),sessionKey=String(started.sessionKey||"");if(!folderId||!sessionKey)throw new Error("নিরাপদ upload session তৈরি হয়নি। Apps Script-এর নতুন deployment দিন।");for(let i=0;i<files.length;i++){const item=files[i];setNotice(`মূল ফাইল ${i+1}/${files.length} নিরাপদে রাখা হচ্ছে...`);await post({action:"upload",reference:ref,folderId,sessionKey,kind:"original",index:i+1,fileName:item.file.name,mimeType:item.file.type,base64:await b64(item.file)});if(clean&&item.file.type.startsWith("image/")){const blob=await cleanImage(item.file);await post({action:"upload",reference:ref,folderId,sessionKey,kind:"clean",index:i+1,fileName:item.file.name.replace(/\.[^.]+$/,"")+"_clean.jpg",mimeType:"image/jpeg",base64:await b64(blob)})}}for(const part of parts){setNotice(`AI/OCR পৃষ্ঠা ${part.page} পাঠানো হচ্ছে...`);await post({action:"upload",reference:ref,folderId,sessionKey,kind:"analysis",page:part.page,fileName:part.name,mimeType:part.blob.type,base64:await b64(part.blob)})}setNotice("Upload সম্পন্ন হয়েছে, রেকর্ড লেখা হচ্ছে...");await post({action:"finish",reference:ref,folderId,sessionKey,options});setState("ok");setNotice(`সফলভাবে জমা হয়েছে। রেফারেন্স: ${ref}`);setName("");setMobile("");setSubject("");setMessage("");setSelection("");files.forEach(x=>x.preview&&URL.revokeObjectURL(x.preview));setFiles([])}catch(error){setState("error");setNotice(error instanceof Error?error.message:"জমা দেওয়া যায়নি। আবার চেষ্টা করুন।")}finally{setBusy(false)}}
 return <main style={shell}><div style={{maxWidth:760,margin:"auto"}}><header><b style={{color:"#176b87"}}>AKB Scan</b><h1>তথ্য / বক্তব্য জমা দিন</h1><p>প্রয়োজনীয় ছবি বা PDF সংযুক্ত করুন।</p></header><form onSubmit={submit} style={card}><div style={grid}><Field label="নাম *"><input value={name} onChange={e=>setName(e.target.value)} style={input}/></Field><Field label="মোবাইল নম্বর *"><input value={mobile} onChange={e=>setMobile(e.target.value)} inputMode="tel" style={input}/></Field></div><Field label="বিষয়"><input value={subject} onChange={e=>setSubject(e.target.value)} style={input}/></Field><Field label="বক্তব্য / বিবরণ *"><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={5} style={input}/></Field><section style={{marginTop:20,borderTop:"1px solid #edf0f3",paddingTop:20}}><b>সংযুক্তি *</b><small style={{display:"block",color:"#667085"}}>ছবি/PDF, সর্বোচ্চ 5টি, মোট 10 MB · {(total/1048576).toFixed(1)} MB</small><div style={{...grid,marginTop:12}}><button type="button" onClick={()=>camera.current?.click()} style={action}><Camera/> ক্যামেরা</button><button type="button" onClick={()=>picker.current?.click()} style={action}><FilePlus2/> ছবি / PDF</button></div><input ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>{add(e.target.files);e.currentTarget.value=""}}/><input ref={picker} hidden type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{add(e.target.files);e.currentTarget.value=""}}/>{files.map((x,i)=><div key={x.id} style={row}><span>{x.preview?<img src={x.preview} alt="" style={{width:45,height:45,objectFit:"cover"}}/>:<UploadCloud/>}</span><b>{i+1}. {x.file.name}</b><button type="button" onClick={()=>remove(x.id)}><Trash2/></button></div>)}<Option checked={clean} change={setClean} title="ছবি পরিষ্কার করুন" text="মূল ফাইলের পাশাপাশি আলাদা _clean কপি রাখবে।"/><Option checked={ocr} change={setOcr} title="লেখা শনাক্ত করুন" text="দৃশ্যমান লেখা বিশ্বস্তভাবে Sheet-এ রাখবে।"/><Option checked={autoSubject} change={setAutoSubject} title="বিষয় তৈরি করুন" text="সংক্ষিপ্ত বিষয় তৈরি করবে।"/>{(ocr||autoSubject)&&<Field label="AI/OCR পৃষ্ঠা (ঐচ্ছিক)"><input value={selection} onChange={e=>setSelection(e.target.value)} placeholder="যেমন 1-3,5 · ফাঁকা রাখলে সব পৃষ্ঠা" style={input}/></Field>}</section>{state!=="idle"&&<div role="status" style={{marginTop:18,padding:12,background:state==="ok"?"#ecfdf3":"#fff1f0",color:state==="ok"?"#067647":"#b42318"}}>{state==="ok"&&<CheckCircle2/>} {notice}</div>}<button disabled={busy} style={primary}>{busy?<><Loader2/> {notice||"জমা হচ্ছে..."}</>:<><Send/> জমা দিন</>}</button></form></div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:7,marginTop:14}}><b>{label}</b>{children}</label>}
function Option({checked,change,title,text}:{checked:boolean;change:(v:boolean)=>void;title:string;text:string}){return <label style={{display:"flex",gap:10,marginTop:10,padding:12,background:"#f7fafc"}}><input type="checkbox" checked={checked} onChange={e=>change(e.target.checked)}/><span><b>{title}</b><small style={{display:"block",color:"#667085"}}>{text}</small></span></label>}
const shell:React.CSSProperties={minHeight:"100vh",background:"#f5f7fb",padding:"24px 14px",color:"#18202a"},card:React.CSSProperties={background:"white",border:"1px solid #e5e7eb",borderRadius:20,padding:"clamp(18px,4vw,30px)"},grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14},input:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #d0d5dd",borderRadius:11,padding:12,font:"inherit"},action:React.CSSProperties={border:"1px solid #cbd5e1",borderRadius:11,padding:12,background:"white",fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center",gap:8},row:React.CSSProperties={display:"grid",gridTemplateColumns:"48px 1fr auto",gap:10,alignItems:"center",padding:9,border:"1px solid #e5e7eb",marginTop:8},primary:React.CSSProperties={width:"100%",marginTop:20,border:0,borderRadius:13,padding:14,fontWeight:800,background:"#176b87",color:"white",display:"flex",alignItems:"center",justifyContent:"center",gap:9};
