"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,FileImage,FileText,Sparkles,Crop,RotateCw,Copy,Trash2,Download,Printer,Undo2,GripVertical,Check,X,SlidersHorizontal,Plus} from "lucide-react";
import {jsPDF} from "jspdf";
import JSZip from "jszip";
import {canvasBlob,defaultCorners,detectDocumentCorners,enhance,fileToImage,FilterName,imageToCanvas,perspectiveCorrect,Point} from "@/lib/scanner";
type PageItem={id:string,name:string,original:HTMLCanvasElement,processed:HTMLCanvasElement,filter:FilterName,corners:Point[]};
const FILTERS:{id:FilterName,label:string}[]=[{id:"auto",label:"Auto / Clean"},{id:"original",label:"Original"},{id:"color",label:"Color Document"},{id:"gray",label:"Grayscale"},{id:"bw",label:"Black & White"},{id:"strong-bw",label:"Strong B&W"},{id:"ink",label:"Ink Saver"},{id:"photo",label:"Photo"}],id=()=>crypto.randomUUID();
function CanvasView({canvas,className=""}:{canvas?:HTMLCanvasElement,className?:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(canvas&&ref.current){ref.current.width=canvas.width;ref.current.height=canvas.height;ref.current.getContext("2d")!.drawImage(canvas,0,0)}},[canvas]);return <canvas ref={ref} className={className}/>}
export default function Home(){
 const [pages,setPages]=useState<PageItem[]>([]),[active,setActive]=useState(0),[busy,setBusy]=useState(""),[compare,setCompare]=useState(100),[cropMode,setCropMode]=useState(false),[advanced,setAdvanced]=useState(false),[strength,setStrength]=useState(65),[ai,setAi]=useState(false),[paper,setPaper]=useState("a4"),[orientation,setOrientation]=useState("portrait"),[margin,setMargin]=useState(10),[fit,setFit]=useState(true),[drag,setDrag]=useState<number|null>(null);
 const images=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),pdfFile=useRef<HTMLInputElement>(null),page=pages[active];
 useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
 const update=(fn:(p:PageItem)=>PageItem)=>setPages(v=>v.map((p,i)=>i===active?fn(p):p));
 async function addImages(files:FileList|null){if(!files?.length)return;setBusy("ছবি প্রস্তুত হচ্ছে…");const items:PageItem[]=[];for(const file of Array.from(files)){const img=await fileToImage(file),s=Math.min(1,2600/Math.max(img.naturalWidth,img.naturalHeight)),c=imageToCanvas(img,Math.round(img.naturalWidth*s),Math.round(img.naturalHeight*s));items.push({id:id(),name:file.name,original:c,processed:enhance(c,"auto",strength),filter:"auto",corners:detectDocumentCorners(c)})}setPages(v=>[...v,...items]);setActive(pages.length);setBusy("")}
 async function addPdf(files:FileList|null){const file=files?.[0];if(!file)return;setBusy("PDF পড়া হচ্ছে…");try{const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="/pdf.worker.min.mjs";const doc=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,items:PageItem[]=[];for(let n=1;n<=doc.numPages;n++){setBusy("PDF পৃষ্ঠা "+n+"/"+doc.numPages+" প্রস্তুত হচ্ছে…");const pg=await doc.getPage(n),base=pg.getViewport({scale:1}),vp=pg.getViewport({scale:Math.min(3,2200/Math.max(base.width,base.height))}),c=document.createElement("canvas");c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await pg.render({canvasContext:c.getContext("2d")!,viewport:vp,canvas:c}).promise;items.push({id:id(),name:file.name+" · "+n,original:c,processed:enhance(c,"auto",strength),filter:"auto",corners:defaultCorners(c.width,c.height)});await new Promise(r=>setTimeout(r,0))}setPages(v=>[...v,...items]);setActive(pages.length)}catch{alert("PDF খোলা যায়নি। Password-protected বা ক্ষতিগ্রস্ত হতে পারে।")}setBusy("")}
 function filter(f:FilterName){if(!page)return;setBusy("Filter প্রয়োগ হচ্ছে…");requestAnimationFrame(()=>{update(p=>({...p,filter:f,processed:enhance(p.original,f,strength)}));setBusy("")})}
 function rotate(){const src=page.original,c=document.createElement("canvas");c.width=src.height;c.height=src.width;const x=c.getContext("2d")!;x.translate(c.width,0);x.rotate(Math.PI/2);x.drawImage(src,0,0);update(p=>({...p,original:c,processed:enhance(c,p.filter,strength),corners:defaultCorners(c.width,c.height)}))}
 function confirmCrop(){const c=perspectiveCorrect(page.original,page.corners);update(p=>({...p,original:c,processed:enhance(c,p.filter,strength),corners:defaultCorners(c.width,c.height)}));setCropMode(false)}
 function reset(){update(p=>({...p,processed:p.original,filter:"original",corners:defaultCorners(p.original.width,p.original.height)}));setCompare(100)}
 function duplicate(){const clone=(c:HTMLCanvasElement)=>imageToCanvas(c,c.width,c.height),n={...page,id:id(),name:page.name+" copy",original:clone(page.original),processed:clone(page.processed),corners:page.corners.map(p=>({...p}))};setPages(v=>[...v.slice(0,active+1),n,...v.slice(active+1)])}
 function remove(){setPages(v=>v.filter((_,i)=>i!==active));setActive(Math.max(0,active-1))}
 async function enhanceAll(){const out:PageItem[]=[];for(let i=0;i<pages.length;i++){setBusy("পৃষ্ঠা "+(i+1)+"/"+pages.length+" পরিষ্কার হচ্ছে…");out.push({...pages[i],filter:"auto",processed:enhance(pages[i].original,"auto",strength)});await new Promise(r=>setTimeout(r,0))}setPages(out);setBusy("")}
 function size():[number,number]{if(paper==="letter")return orientation==="portrait"?[215.9,279.4]:[279.4,215.9];return orientation==="portrait"?[210,297]:[297,210]}
 async function exportPdf(print=false){const [pw,ph]=size(),pdf=new jsPDF({unit:"mm",format:[pw,ph],orientation:pw>ph?"landscape":"portrait",compress:true});setBusy("PDF তৈরি হচ্ছে…");for(let i=0;i<pages.length;i++){if(i)pdf.addPage([pw,ph],pw>ph?"landscape":"portrait");const c=pages[i].processed,aw=pw-margin*2,ah=ph-margin*2,r=fit?Math.min(aw/c.width,ah/c.height):Math.min(1,aw/c.width),w=c.width*r,h=c.height*r;pdf.addImage(c.toDataURL("image/jpeg",.94),"JPEG",(pw-w)/2,(ph-h)/2,w,h,undefined,"FAST")}if(print){const url=URL.createObjectURL(pdf.output("blob")),win=window.open(url,"_blank");setTimeout(()=>{win?.print();URL.revokeObjectURL(url)},800)}else pdf.save("AKB-Scan.pdf");setBusy("")}
 async function saveCurrent(type:"jpeg"|"png"){const a=document.createElement("a");a.href=URL.createObjectURL(await canvasBlob(page.processed,"image/"+type,.96));a.download="AKB-Scan-"+(active+1)+(type==="jpeg"?".jpg":".png");a.click()}
 async function saveAll(){setBusy("ছবিগুলো ZIP হচ্ছে…");const z=new JSZip();for(let i=0;i<pages.length;i++)z.file("AKB-Scan-"+(i+1)+".jpg",await canvasBlob(pages[i].processed));const a=document.createElement("a");a.href=URL.createObjectURL(await z.generateAsync({type:"blob"}));a.download="AKB-Scan-pages.zip";a.click();setBusy("")}
 return <main className="app"><header><div className="brand"><span>AKB</span><div><h1>AKB Scan</h1><small>Processed on your device</small></div></div><div className="top-actions"><label><input type="checkbox" checked={ai} onChange={e=>setAi(e.target.checked)}/><Sparkles/> AI Enhance</label><button disabled={!pages.length} onClick={()=>exportPdf()}><Download/> PDF</button><button disabled={!pages.length} onClick={()=>exportPdf(true)}><Printer/> Print</button></div></header>
 {!pages.length?<section className="home"><div className="hero-tag"><Sparkles/> Clean scans. Less ink.</div><h2>Make every document<br/><em>print ready.</em></h2><p>ছবি বা PDF থেকে shadow, বাঁকাভাব ও ময়লা background সরিয়ে scanner-এর মতো পরিষ্কার document তৈরি করুন। কোনো upload প্রয়োজন নেই।</p><div className="import-grid"><button onClick={()=>camera.current?.click()}><Camera/><b>Scan with Camera</b><small>মোবাইল ক্যামেরা দিয়ে তুলুন</small></button><button onClick={()=>images.current?.click()}><FileImage/><b>Import Images</b><small>JPG, PNG, WebP · Multiple</small></button><button onClick={()=>pdfFile.current?.click()}><FileText/><b>Import PDF</b><small>Multi-page PDF খুলুন</small></button></div><div className="workflow">Import / Camera <i>→</i> Auto Fix <i>→</i> Crop <i>→</i> Filter <i>→</i> Print / Export</div></section>:
 <div className="workspace"><aside className="pages-panel"><div className="panel-head"><b>Pages</b><button onClick={()=>images.current?.click()}><Plus/> Add</button></div><div className="thumbs">{pages.map((p,i)=><button draggable key={p.id} onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag===null)return;const n=[...pages],x=n.splice(drag,1)[0];n.splice(i,0,x);setPages(n);setActive(i);setDrag(null)}} onClick={()=>setActive(i)} className={i===active?"active":""}><GripVertical/><CanvasView canvas={p.processed}/><span>{i+1}</span></button>)}</div><button className="enhance-all" onClick={enhanceAll}><Sparkles/> Enhance All</button></aside>
 <section className="stage"><div className="stage-bar"><span>Page <b>{active+1}</b> of {pages.length}</span><div><button onClick={rotate}><RotateCw/> Rotate</button><button className={cropMode?"active":""} onClick={()=>setCropMode(v=>!v)}><Crop/> Crop</button><button onClick={reset}><Undo2/> Reset</button></div></div><div className="paper-zone"><div className="paper" style={{aspectRatio:page.processed.width+"/"+page.processed.height}}><CanvasView canvas={page.original} className="base-canvas"/><div className="after-layer" style={{clipPath:"inset(0 "+(100-compare)+"% 0 0)"}}><CanvasView canvas={page.processed}/></div>{compare<100&&<div className="divider" style={{left:compare+"%"}}/>}{cropMode&&<CropOverlay page={page} onChange={c=>update(p=>({...p,corners:c}))}/>}</div></div><div className="compare"><span>Before</span><input aria-label="Before and after comparison" type="range" min="0" max="100" value={compare} onChange={e=>setCompare(+e.target.value)}/><span>After</span></div></section>
 <aside className="tools"><h3>Auto Fix</h3><p>Shadow, paper tone ও contrast ঠিক করুন</p><button className="auto-fix" onClick={()=>filter("auto")}><Sparkles/> Apply Auto Fix</button>{cropMode&&<div className="crop-confirm"><button onClick={()=>setCropMode(false)}><X/></button><button onClick={confirmCrop}><Check/> Crop confirm</button></div>}<h3>Filters</h3><div className="filters">{FILTERS.map(f=><button key={f.id} className={page.filter===f.id?"active":""} onClick={()=>filter(f.id)}><span className={"filter-chip "+f.id}/>{f.label}</button>)}</div><button className="advanced-toggle" onClick={()=>setAdvanced(v=>!v)}><SlidersHorizontal/> Page setup <span>{advanced?"−":"+"}</span></button>{advanced&&<div className="advanced"><label>Clean strength<input type="range" min="20" max="100" value={strength} onChange={e=>setStrength(+e.target.value)} onPointerUp={()=>filter(page.filter)}/></label><label>Paper<select value={paper} onChange={e=>setPaper(e.target.value)}><option value="a4">A4</option><option value="letter">Letter</option><option value="original">Original</option></select></label><label>Orientation<select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label>Margin: {margin} mm<input type="range" min="0" max="25" value={margin} onChange={e=>setMargin(+e.target.value)}/></label><label className="check"><input type="checkbox" checked={fit} onChange={e=>setFit(e.target.checked)}/> Fit to page</label></div>}<div className="page-actions"><button onClick={duplicate}><Copy/>Duplicate</button><button className="danger" onClick={remove}><Trash2/>Delete</button></div><div className="exports"><button onClick={()=>exportPdf()}>Multi-page PDF</button><button onClick={()=>saveCurrent("jpeg")}>Current JPG</button><button onClick={()=>saveCurrent("png")}>Current PNG</button><button onClick={saveAll}>All images (.zip)</button></div></aside></div>}
 <input ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>addImages(e.target.files)}/><input ref={images} hidden type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>addImages(e.target.files)}/><input ref={pdfFile} hidden type="file" accept="application/pdf" onChange={e=>addPdf(e.target.files)}/>{busy&&<div className="busy"><span/><b>{busy}</b></div>}{ai&&<div className="toast">AI provider configured নয়। Device-side enhancement চালু আছে।</div>}</main>}
function CropOverlay({page,onChange}:{page:PageItem,onChange:(p:Point[])=>void}){const ref=useRef<HTMLDivElement>(null);function start(i:number,e:React.PointerEvent){e.currentTarget.setPointerCapture(e.pointerId);const move=(ev:PointerEvent)=>{const r=ref.current!.getBoundingClientRect(),p=page.corners.map(x=>({...x}));p[i]={x:Math.max(0,Math.min(page.original.width,(ev.clientX-r.left)/r.width*page.original.width)),y:Math.max(0,Math.min(page.original.height,(ev.clientY-r.top)/r.height*page.original.height))};onChange(p)},up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}return <div ref={ref} className="crop-overlay"><svg viewBox={"0 0 "+page.original.width+" "+page.original.height} preserveAspectRatio="none"><polygon points={page.corners.map(p=>p.x+","+p.y).join(" ")}/></svg>{page.corners.map((p,i)=><button aria-label={"Corner "+(i+1)} key={i} onPointerDown={e=>start(i,e)} style={{left:(p.x/page.original.width*100)+"%",top:(p.y/page.original.height*100)+"%"}}/>)}</div>}
