const ROOT_FOLDER_ID="1mzdpQMxR_lW27YmdpO51VsXptAlmbdQO";
const SHEET_ID="1JmHABfFYfNHtSeZbg6O3TV7egfDI9dF3VuBKLennujw";
const MAX_ORIGINAL_FILES=5,MAX_ORIGINAL_BYTES=10*1024*1024,MAX_SINGLE_BYTES=10*1024*1024,MAX_DERIVED_BYTES=30*1024*1024,SESSION_TTL_MS=2*60*60*1000;
function reply(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function sheet(){const s=SpreadsheetApp.openById(SHEET_ID).getSheetByName("Responses");if(!s)throw new Error('Sheet "Responses" পাওয়া যায়নি');return s}
function sessionId(key){const digest=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(key));return "UPLOAD_"+Utilities.base64EncodeWebSafe(digest).replace(/=+$/g,"")}
function loadSession(key){if(!key)throw new Error("Upload session key প্রয়োজন");const p=PropertiesService.getScriptProperties(),id=sessionId(key),raw=p.getProperty(id);if(!raw)throw new Error("Upload session পাওয়া যায়নি বা মেয়াদ শেষ");const s=JSON.parse(raw);if(Date.now()>s.expiresAt){p.deleteProperty(id);throw new Error("Upload session-এর মেয়াদ শেষ। আবার শুরু করুন।")}return {id:id,state:s}}
function saveSession(id,state){PropertiesService.getScriptProperties().setProperty(id,JSON.stringify(state))}
function inRoot(folder){const parents=folder.getParents();while(parents.hasNext())if(parents.next().getId()===ROOT_FOLDER_ID)return true;return false}
function validateSession(body){const loaded=loadSession(body.sessionKey),s=loaded.state;if(String(body.reference)!==s.reference||String(body.folderId)!==s.folderId)throw new Error("Upload session মিলছে না");const folder=DriveApp.getFolderById(s.folderId);if(!inRoot(folder))throw new Error("অনুমোদিত Drive folder নয়");return {id:loaded.id,state:s,folder:folder}}
function detectedMime(bytes){const u=n=>bytes[n]&255,ascii=(a,b)=>bytes.slice(a,b).map(x=>String.fromCharCode(x&255)).join("");if(bytes.length>=4&&u(0)===0xFF&&u(1)===0xD8&&u(2)===0xFF)return "image/jpeg";if(bytes.length>=8&&u(0)===0x89&&u(1)===0x50&&u(2)===0x4E&&u(3)===0x47)return "image/png";if(bytes.length>=12&&ascii(0,4)==="RIFF"&&ascii(8,12)==="WEBP")return "image/webp";if(bytes.length>=5&&ascii(0,5)==="%PDF-")return "application/pdf";throw new Error("শুধু JPEG, PNG, WebP বা PDF গ্রহণ করা হয়")}
function doPost(e){try{const body=JSON.parse(e.postData&&e.postData.contents||"{}"),action=String(body.action||"");if(action==="start")return startSubmission(body);if(action==="upload")return uploadPart(body);if(action==="finish")return finishSubmission(body);return reply({ok:false,error:"Unknown action"})}catch(error){return reply({ok:false,error:String(error&&error.message||error)})}}
function startSubmission(body){if(!String(body.reference||"")||!String(body.name||""))throw new Error("Reference এবং name প্রয়োজন");const lock=LockService.getScriptLock();lock.waitLock(15000);try{const root=DriveApp.getFolderById(ROOT_FOLDER_ID),folder=root.createFolder(safe(body.reference+"_"+body.name)),s=sheet(),options=normalizeOptions(body.options||{});s.appendRow([Math.max(1,s.getLastRow()),new Date(),body.reference,body.name,body.note||"","","",folder.getUrl(),"",optionLabel(options),"Receiving",""]);const row=s.getLastRow();formatSubmissionRow(s,row);const key=Utilities.getUuid()+Utilities.getUuid(),state={reference:String(body.reference),folderId:folder.getId(),row:row,expiresAt:Date.now()+SESSION_TTL_MS,originalBytes:0,derivedBytes:0,originalCount:0,options:options,originals:[],cleans:[],analysis:[]};saveSession(sessionId(key),state);return reply({ok:true,folderId:folder.getId(),folderUrl:folder.getUrl(),sessionKey:key})}finally{lock.releaseLock()}}
function uploadPart(body){const verified=validateSession(body),state=verified.state,kind=String(body.kind||"original");if(["original","clean","analysis"].indexOf(kind)<0)throw new Error("Invalid upload kind");const bytes=Utilities.base64Decode(String(body.base64||""));if(!bytes.length||bytes.length>MAX_SINGLE_BYTES)throw new Error("ফাইলটি খালি অথবা 10 MB-এর বেশি");const mime=detectedMime(bytes);if(kind==="clean"&&!/^image\//.test(mime))throw new Error("Clean copy অবশ্যই image হবে");if(kind==="original"){if(state.originalCount>=MAX_ORIGINAL_FILES)throw new Error("সর্বোচ্চ 5টি মূল ফাইল");if(state.originalBytes+bytes.length>MAX_ORIGINAL_BYTES)throw new Error("মূল ফাইল মোট 10 MB-এর বেশি")}else if(state.derivedBytes+bytes.length>MAX_DERIVED_BYTES)throw new Error("Prepared copy মোট 30 MB-এর বেশি");let target=verified.folder;if(kind==="analysis"){if(!state.analysisFolderId)state.analysisFolderId=verified.folder.createFolder(".ai-pages").getId();target=DriveApp.getFolderById(state.analysisFolderId)}const file=target.createFile(Utilities.newBlob(bytes,mime,safe(body.fileName)));const item={id:file.getId(),url:file.getUrl(),index:Number(body.index||0),page:Number(body.page||0),mime:mime};if(kind==="original"){state.originals.push(item);state.originalCount++;state.originalBytes+=bytes.length}else{state[kind==="clean"?"cleans":"analysis"].push(item);state.derivedBytes+=bytes.length}saveSession(verified.id,state);return reply({ok:true,fileUrl:file.getUrl()})}
function finishSubmission(body){const verified=validateSession(body),state=verified.state,s=sheet();if(!state.originals.length)throw new Error("কোনো মূল file পাওয়া যায়নি");const row=Number(state.row),urls=state.originals.concat(state.cleans).map(x=>x.url);s.getRange(row,9).setValue(urls.join("\n"));s.getRange(row,11).setValue("Received");s.getRange(row,12).setValue("");SpreadsheetApp.flush();let aiStatus="Not requested";try{const o=normalizeOptions(state.options||body.options||{});if(o.extractText||o.autoSubject){const source=state.analysis.length?state.analysis:state.originals,result=analyzeSubmissionFiles(source,o);if(result.subject)s.getRange(row,6).setValue(result.subject);if(result.text)s.getRange(row,7).setValue(result.text);if(result.shortName)renameSubmissionFiles(state,result.shortName);s.getRange(row,11).setValue("AI OK");s.getRange(row,12).setValue("AI OK");aiStatus="AI OK"}}catch(error){aiStatus=String(error&&error.message||error);s.getRange(row,12).setValue(aiStatus)}finally{if(state.analysisFolderId)try{DriveApp.getFolderById(state.analysisFolderId).setTrashed(true)}catch(_){}PropertiesService.getScriptProperties().deleteProperty(verified.id);formatSubmissionRow(s,row);SpreadsheetApp.flush()}return reply({ok:true,status:"Received",aiStatus:aiStatus})}
function analyzeSubmissionFiles(items,o){const props=PropertiesService.getScriptProperties(),key=props.getProperty("GEMINI_API_KEY");if(!key)throw new Error("GEMINI_API_KEY Script Property পাওয়া যায়নি");const model=props.getProperty("GEMINI_MODEL")||"gemini-3.5-flash",parts=[{text:["সব attachment upload order অনুযায়ী একই document-এর page। শুধু একবার বিশ্লেষণ করো।","text-এ দৃশ্যমান লেখা যতটা সম্ভব হুবহু রাখো। নাম, passport/ID/reference number, তারিখ, amount, stamp ও signature-এর লেখা rewrite বা invent করবে না। অস্পষ্ট হলে [অস্পষ্ট] লিখবে।",o.extractText?"পূর্ণ faithful OCR text দাও।":"text খালি রাখো।",o.autoSubject?"subject-এ সংক্ষিপ্ত অর্থবহ বাংলা বিষয় দাও।":"subject খালি রাখো।","shortName সবসময় document content থেকে subject-এর চেয়েও ছোট 2-6 শব্দে দাও। extension ও / \\ : * ? \" < > | দেবে না।","শুধু JSON: {\"text\":\"...\",\"subject\":\"...\",\"shortName\":\"...\"}"].join("\n")}];items.sort((a,b)=>(a.page||a.index)-(b.page||b.index)).forEach(x=>{const blob=DriveApp.getFileById(x.id).getBlob();parts.push({inlineData:{mimeType:blob.getContentType(),data:Utilities.base64Encode(blob.getBytes())}})});const endpoint="https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(model)+":generateContent?key="+encodeURIComponent(key),response=UrlFetchApp.fetch(endpoint,{method:"post",contentType:"application/json",payload:JSON.stringify({contents:[{role:"user",parts:parts}],generationConfig:{temperature:.1,responseMimeType:"application/json"}}),muteHttpExceptions:true}),code=response.getResponseCode(),body=response.getContentText();if(code<200||code>=300)throw new Error("Gemini HTTP "+code+": "+body.slice(0,500));const parsed=JSON.parse(body),text=parsed&&parsed.candidates&&parsed.candidates[0]&&parsed.candidates[0].content&&parsed.candidates[0].content.parts[0].text;if(!text)throw new Error("Gemini কোনো result দেয়নি");const result=JSON.parse(String(text).replace(/^```json\s*/i,"").replace(/```$/i,"").trim());return {text:o.extractText?String(result.text||""):"",subject:o.autoSubject?String(result.subject||""):"",shortName:safeShortName(result.shortName||result.subject||"Document")}}
function renameSubmissionFiles(state,name){const base=safeShortName(name),many=state.originals.length>1;state.originals.forEach((x,i)=>{const f=DriveApp.getFileById(x.id),old=f.getName(),dot=old.lastIndexOf("."),ext=dot>0?old.slice(dot):"",number=many?"_"+String(i+1).padStart(2,"0"):"";f.setName(base+number+ext)});state.cleans.forEach(x=>{const i=Math.max(1,Number(x.index||1)),number=many?"_"+String(i).padStart(2,"0"):"";DriveApp.getFileById(x.id).setName(base+number+"_clean.jpg")})}
function normalizeOptions(o){return {enhance:!!o.enhance,extractText:o.extractText!==false,autoSubject:o.autoSubject!==false,pageSelection:String(o.pageSelection||"")}}
function optionLabel(o){return JSON.stringify(o)}
function formatSubmissionRow(s,row){s.getRange(row,1,1,12).setWrap(false).setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP).setVerticalAlignment("middle");s.setRowHeightsForced(row,1,28)}
function fixOldResponses(){const s=sheet(),n=s.getLastRow()-1;if(n<1)return;s.getRange(2,1,n,12).setWrap(false).setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP).setVerticalAlignment("middle");s.setRowHeightsForced(2,n,28)}
function repairOldSubjectText(){const s=sheet(),n=s.getLastRow()-1;if(n<1)return;const r=s.getRange(2,6,n,2),v=r.getValues();v.forEach(x=>{const a=String(x[0]||"").trim(),b=String(x[1]||"").trim();if((a.length>=180||a.indexOf("\n")>=0)&&(!b||b.length<120)){x[1]=x[0];x[0]=b}});r.setValues(v);fixOldResponses()}
function safeShortName(v){return String(v||"Document").replace(/[\/:*?"<>|\x00-\x1F]/g," ").replace(/\s+/g," ").trim().slice(0,80)||"Document"}
function safe(v){return String(v||"").replace(/[\/:*?"<>|\x00-\x1F]/g,"_").slice(0,140)||"attachment"}
